// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Models;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(GoodsDetailContext))]
    partial class GoodsDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Models.GoodsDetail", b =>
                {
                    b.Property<int>("GoodsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GoodsBrand")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoodsModel")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoodsName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoodsNo")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoodsSerailNumber")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GoodsID");

                    b.ToTable("GoodsDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
